### ISSUE TITLE
Кривая ширина для малого шрифта

### ISSUE THREAD

**Issue by TestOO7** [HellbringerOnline/Silent-Hill-2-Enchanced-Edition-Rus#1]
Ширина символом малого шрифта не соответствует замененной кириллицей. Для примера выдранная ширина от исполняемого файла, отредактированного WarMaker:
в fontwdata.bin со смещения 0x00000180 прописать 0907070609070C070A0A09090C0A0A0A070807080A080B0A0D0D090C07080D080606060507050A05070707070907060707050607090608070B0B080A06050A07
Станет веселее, но до идеала далеко.

**Comment by HellbringerOnline** [comment]
> Ширина символом малого шрифта не соответствует замененной кириллицей. Для примера выдранная ширина от исполняемого файла, отредактированного WarMaker:
> в fontwdata.bin со смещения 0x00000180 прописать 0907070609070C070A0A09090C0A0A0A070807080A080B0A0D0D090C07080D080606060507050A05070707070907060707050607090608070B0B080A06050A07
> Станет веселее, но до идеала далеко.

Будьте добры скрины до и после. Из какой версии приложения вы выдирали `fontwdata.bin`? Смещение для русских символов в мой версии `fontwdata.bin` начинается с другой позиции.
![61175267-41a14200-a5bd-11e9-8020-f09d56284d2d](https://user-images.githubusercontent.com/14059683/62801764-7d192880-baf7-11e9-8543-7e59e0ff2765.png)

**Comment by TestOO7** [comment]
Как я понял в fontwdata.bin лежат две последовательности длиной по 0xE0 для каждого из шрифтов (нормальны и малый), скрин малого (кириллица продублирована для совместимости с пиратками разными, там ASCII/ANSI:
![_000](https://user-images.githubusercontent.com/53950991/62804331-a0db6f00-baf5-11e9-9237-050c28427973.png)
У Вас в редакторе смещения слева в десятичном виде показаны. Букву Ё можно везде заменить на Е (вроде оно так и сделано в переводах пиратских).
Разница между Вашим и правкой:
![000](https://user-images.githubusercontent.com/53950991/62804522-3840c200-baf6-11e9-8931-76efcdaaf070.png)
![001](https://user-images.githubusercontent.com/53950991/62804525-3bd44900-baf6-11e9-8c40-27f07f301850.png)

**Comment by HellbringerOnline** [comment]
@TestOO7  по моей информации `fontwdata.bin` содержит информации о смещении первых 224 символов https://user-images.githubusercontent.com/27395260/60759556-1931aa80-9ff5-11e9-8a60-6a1a1207db77.png
Данная проблема уже обсуждалась, внятного ответа я не получил.
Приложите вашу версию файла `fontwdata.bin`, и я подгоню смещения в будущем, если ваша теория подтвердится.

**Comment by TestOO7** [comment]
Все верно про ширину первых 224 символов, только таких последовательности там две, для "нормального" (normal) и "малого" (small) шрифтов в именовании от belek666.
![fontdata](https://user-images.githubusercontent.com/53950991/62818917-d4021a80-bb56-11e9-8962-1dbc5be702a6.png)
![fonts](https://user-images.githubusercontent.com/53950991/62818919-d8c6ce80-bb56-11e9-9f71-0b91a7c85d4a.png)

[fontwdata.zip](https://github.com/HellbringerOnline/Silent-Hill-2-Enchanced-Edition-Rus/files/3488611/fontwdata.zip)

**Comment by HellbringerOnline** [comment]
Подогнал выравнивание, со временем подгоню точнее.
