### ISSUE TITLE
Архив первоначальных вариантов переводов

### ISSUE THREAD

**Issue by TestOO7** [HellbringerOnline/Silent-Hill-2-Enchanced-Edition-Rus#2]
Можете прикрепить исходные mes файлы переводов? Проблемы со строчными 'а' и 'р' у имеющихся у меня вариантов находятся в разных местах, скорее это был проблема софта, которым редактировали/конвертировали файлы. У Вас есть какой-то валидатор или переводы вручную проверяются? Прикрепил имеющиеся у меня файлы (оригинальные и после конвертации), в переводе от Ashigaru в файле stage_apart_w2f_msg_e.mes испорчен заголовок (неправильные смещения), у Вас другая версия перевода получается. Может как-то скооперироваться, чтобы не делать одно и тоже?
[sh2ru.zip](https://github.com/HellbringerOnline/Silent-Hill-2-Enchanced-Edition-Rus/files/3490142/sh2ru.zip)

**Comment by HellbringerOnline** [comment]
@TestOO7 А что вы конкретно делаете? Исходные файлы я удалил уже, 2 перевода лежит на playground, 2 на zonofgames. Перевод я проверяю только от Ashigaru по мере прохождения игры. Возможно переводы забагались при конверте, возможно изначально такие кривые были.
Заголовок я фиксил сам.
