### ISSUE TITLE
Несоответствия в инструкции

### ISSUE THREAD

**Issue by PavlikBender** [HellbringerOnline/Silent-Hill-2-Enchanced-Edition-Rus#4]
Пункт 4 инструкции, указывает о замене файла start01.tex, но в директории также есть файл start00.tex, надо ли его заменять?
Продолжая по тому же пункту нужно заменить файл exe_str.txt в папке *\Silent Hill 2\sh2e\text, но по данной директории нет такого файла и некоторые менюшки в игре остаются на английском.

**Comment by HellbringerOnline** [comment]
Проект не стоит на месте, обновил инструкцию, все должно работать.
