### ISSUE TITLE
Ломается перевод на паузе

### ISSUE THREAD

**Issue by dante3732** [HellbringerOnline/Silent-Hill-2-Enchanced-Edition-Rus#5]
Возможно при активации русских текстур в лаунчере.
![image](https://user-images.githubusercontent.com/66036249/200789092-696eac23-696f-4f90-bc9e-77048a262882.png)

**Comment by HellbringerOnline** [comment]
> Возможно при активации русских текстур в лаунчере. ![image](https://user-images.githubusercontent.com/66036249/200789092-696eac23-696f-4f90-bc9e-77048a262882.png)

о каком лаунчере идет речь?

**Comment by dante3732** [comment]
![image](https://user-images.githubusercontent.com/66036249/200855929-27da32ea-9102-469b-94bc-6287b81dd924.png)

**Comment by HellbringerOnline** [comment]
> ![image](https://user-images.githubusercontent.com/66036249/200855929-27da32ea-9102-469b-94bc-6287b81dd924.png)
я не поддерживаю совместимость со сторонними лаунчерами, но возможно добавлю локализованные текстуры в перевод.

**Comment by HellbringerOnline** [comment]
> ![image](https://user-images.githubusercontent.com/66036249/200855929-27da32ea-9102-469b-94bc-6287b81dd924.png)

можешь попробовать открыть r_menu_e.res в блокноте и сохранить в другой кодировке (UTF-8), может быть поможет

**Comment by dante3732** [comment]
Да я уже прошёл и удалил всё, там проблемы были только в меню паузы. А остальной текст отображался как надо.
