### ISSUE TITLE
в enhanced edition добавили поддержку языковых паков

### ISSUE THREAD

**Issue by 60d74** [HellbringerOnline/Silent-Hill-2-Enchanced-Edition-Rus#6]
в последнем обновлении enhanced edition добавили поддержку языковых паков (https://enhanced.townofsilenthill.com/SH2/languagepacks.htm), которые не заменяют оригинальные файлы игры и их легче устанавливать, предлагаю вам переделать свой под такой манер

**Comment by HellbringerOnline** [comment]
Спасибо посмотрим

**Comment by HellbringerOnline** [comment]
обновлено
